<a href="https://colab.research.google.com/github/keshavsoliwal911-netizen/House_price_prediction/blob/main/Housepriceprdeiction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
house = pd.read_csv('housing.csv')
house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND

In [3]:
X = house.drop(['median_house_value'], axis=1)
y = house['median_house_value']

In [4]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,INLAND

In [5]:
y

0        452600
1        358500
2        352100
3        341300
4        342200
          ...
20635     78100
20636     77100
20637     92300
20638     84700
20639     89400
Name: median_house_value, Length: 20640, dtype: int64

In [6]:
np.corrcoef(X['median_income'], y)

array([[1.        , 0.68807521],
       [0.68807521, 1.        ]])

In [7]:
np.corrcoef(X['median_income'], y)[0,1]

np.float64(0.6880752079585478)

In [8]:
for i in X:
    if i == 'ocean_proximity':
        continue
    print(f"Feature name: {i}")
    r = np.corrcoef(X[i], y)[0,1]
    print(f"correlation: {r}")
    print()

Feature name: longitude
correlation: -0.04596661511797843

Feature name: latitude
correlation: -0.14416027687465927

Feature name: housing_median_age
correlation: 0.10562341249320994

Feature name: total_rooms
correlation: 0.13415311380656308

Feature name: total_bedrooms
correlation: nan

Feature name: population
correlation: -0.02464967888889488

Feature name: households
correlation: 0.06584265057005646

Feature name: median_income
correlation: 0.6880752079585478

In [9]:
new_feature = X['latitude'] + X['longitude']
new_feature

0       -84.35
1       -84.36
2       -84.39
3       -84.40
4       -84.40
         ...
20635   -81.61
20636   -81.72
20637   -81.79
20638   -81.89
20639   -81.87
Length: 20640, dtype: float64

In [10]:
np.corrcoef(new_feature, y)

array([[ 1.        , -0.49151968],
       [-0.49151968,  1.        ]])

In [11]:
X.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY

In [12]:
y.head()

0    452600
1    358500
2    352100
3    341300
4    342200
Name: median_house_value, dtype: int64

In [13]:
X.shape

(20640, 9)

In [14]:
size = X.shape[0]
size

20640

In [15]:
test_size = 0.2

In [16]:
testing_size = int(size * 0.2)
testing_size

4128

In [17]:
training_size = size - testing_size
training_size

16512

In [18]:
X.iloc[:training_size]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
16507,-121.11,37.74,11,3886,599.0,1605,529,4.4213,INLAND
16508,-121.10,37.80,35,1853,331.0,958,340,3.3578,INLAND
16509,-121.11,37.76,22,2606,411.0,1252,397,4.1833,INLAND
16510,-121.16,37.73,7,4956,941.0,3006,915,3.4426,INLAND
16511,-121.25,37.76,22,2430,417.0,1292,391,3.4009,INLAND

In [19]:
X.iloc[training_size:]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16512,-121.22,37.72,34,2123,387.0,1310,368,2.6368,INLAND
16513,-121.22,37.81,17,2879,542.0,1802,530,3.6378,INLAND
16514,-121.22,37.80,28,2608,576.0,1719,554,2.1186,INLAND
16515,-121.22,37.80,37,1038,222.0,521,211,2.1250,INLAND
16516,-121.21,37.81,18,2404,498.0,1531,506,2.9950,INLAND
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,INLAND

In [20]:
X = house.drop(['median_house_value'], axis=1)
y = house['median_house_value']

In [21]:
def train_test_split(X, y, test_size=0.2):
    size = X.shape[0]
    testing_size = int(size * test_size)
    training_size = size - testing_size

    train_X = X.iloc[:training_size]
    test_X = X.iloc[training_size:]

    train_y = y.iloc[:training_size]
    test_y = y.iloc[training_size:]

    return train_X, test_X, train_y, test_y

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [23]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
16507,-121.11,37.74,11,3886,599.0,1605,529,4.4213,INLAND
16508,-121.10,37.80,35,1853,331.0,958,340,3.3578,INLAND
16509,-121.11,37.76,22,2606,411.0,1252,397,4.1833,INLAND
16510,-121.16,37.73,7,4956,941.0,3006,915,3.4426,INLAND
16511,-121.25,37.76,22,2430,417.0,1292,391,3.4009,INLAND

In [24]:
y_train

0        452600
1        358500
2        352100
3        341300
4        342200
          ...
16507    182700
16508    149000
16509    192100
16510    139000
16511    182400
Name: median_house_value, Length: 16512, dtype: int64

In [25]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16512,-121.22,37.72,34,2123,387.0,1310,368,2.6368,INLAND
16513,-121.22,37.81,17,2879,542.0,1802,530,3.6378,INLAND
16514,-121.22,37.80,28,2608,576.0,1719,554,2.1186,INLAND
16515,-121.22,37.80,37,1038,222.0,521,211,2.1250,INLAND
16516,-121.21,37.81,18,2404,498.0,1531,506,2.9950,INLAND
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,INLAND

In [26]:
y_test

16512    165600
16513    126100
16514     94400
16515     91900
16516    124300
          ...
20635     78100
20636     77100
20637     92300
20638     84700
20639     89400
Name: median_house_value, Length: 4128, dtype: int64

In [27]:
l = [10,20,30,40,50,60,70,80]

In [28]:
np.random.shuffle(l)
l

[70, 40, 60, 10, 30, 20, 80, 50]

In [29]:
size
indexes = np.arange(size)
indexes

array([    0,     1,     2, ..., 20637, 20638, 20639])

In [30]:
np.random.shuffle(indexes)

In [31]:
indexes

array([ 4845, 15524, 19329, ...,  3274,   349,  9741])

In [32]:
def train_test_split(X, y, test_size=0.2):
    np.random.seed(123)
    size = X.shape[0]
    indexes = np.arange(size)
    np.random.shuffle(indexes)

    testing_size = int(size * test_size)
    training_size = size - testing_size

    train_idx = indexes[:training_size]
    test_idx = indexes[training_size:]

    train_X = X.iloc[train_idx]
    test_X = X.iloc[test_idx]
    train_y = y.iloc[train_idx]
    test_y = y.iloc[test_idx]

    return train_X, test_X, train_y, test_y

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [34]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
19121,-122.64,38.24,40,1974,410.0,1039,398,3.7917,<1H OCEAN
20019,-119.05,36.09,9,3297,568.0,1749,568,4.0217,INLAND
15104,-116.98,32.85,12,3570,713.0,3321,666,4.0882,<1H OCEAN
3720,-118.42,34.20,27,3201,970.0,3403,948,2.2377,<1H OCEAN
8938,-118.47,34.01,41,2704,557.0,1047,478,4.4211,<1H OCEAN

In [35]:
y_train.head()

19121    151600
20019     99200
15104    134500
3720     231700
8938     462900
Name: median_house_value, dtype: int64

In [36]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
19121,-122.64,38.24,40,1974,410.0,1039,398,3.7917,<1H OCEAN
20019,-119.05,36.09,9,3297,568.0,1749,568,4.0217,INLAND
15104,-116.98,32.85,12,3570,713.0,3321,666,4.0882,<1H OCEAN
3720,-118.42,34.20,27,3201,970.0,3403,948,2.2377,<1H OCEAN
8938,-118.47,34.01,41,2704,557.0,1047,478,4.4211,<1H OCEAN

In [37]:
X_train['ocean_proximity'].value_counts() / X_train.shape[0] * 100

ocean_proximity
<1H OCEAN     44.295058
INLAND        31.801114
NEAR OCEAN    12.645349
NEAR BAY      11.234254
ISLAND         0.024225
Name: count, dtype: float64

In [38]:
X_test['ocean_proximity'].value_counts() / X_test.shape[0] * 100

ocean_proximity
<1H OCEAN     44.137597
INLAND        31.492248
NEAR OCEAN    13.808140
NEAR BAY      10.537791
ISLAND         0.024225
Name: count, dtype: float64

In [39]:
l

[70, 40, 60, 10, 30, 20, 80, 50]

In [40]:
l = [1,2,3,4,5,6,7,8,9,10]
np.random.seed(123)
np.random.shuffle(l)
l

[5, 1, 8, 6, 9, 4, 2, 7, 10, 3]

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=123)

In [43]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
9950,-122.33,38.38,28,1020,169.0,504,164,4.5694,INLAND
3547,-118.60,34.26,18,6154,1070.0,3010,1034,5.6392,<1H OCEAN
4448,-118.21,34.07,47,1346,383.0,1452,371,1.7292,<1H OCEAN
6984,-118.02,33.96,36,2071,398.0,988,404,4.6226,<1H OCEAN
4432,-118.20,34.08,49,1320,309.0,1405,328,2.4375,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
7763,-118.10,33.91,36,726,NaN,490,130,3.6389,<1H OCEAN
15377,-117.24,33.37,14,4687,793.0,2436,779,4.5391,<1H OCEAN
17730,-121.76,37.33,5,4153,719.0,2435,697,5.6306,<1H OCEAN
15725,-122.44,37.78,44,1545,334.0,561,326,3.8750,NEAR BAY
19966,-119.08,36.21,20,1911,389.0,1241,348,2.5156,INLAND

In [44]:
y_train

9950     287500
3547     271500
4448     191700
6984     219700
4432     114000
          ...
7763     167600
15377    180900
17730    286200
15725    412500
19966     59300
Name: median_house_value, Length: 16512, dtype: int64

In [45]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
19121,-122.64,38.24,40,1974,410.0,1039,398,3.7917,<1H OCEAN
20019,-119.05,36.09,9,3297,568.0,1749,568,4.0217,INLAND
15104,-116.98,32.85,12,3570,713.0,3321,666,4.0882,<1H OCEAN
3720,-118.42,34.20,27,3201,970.0,3403,948,2.2377,<1H OCEAN
8938,-118.47,34.01,41,2704,557.0,1047,478,4.4211,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
313,-122.19,37.77,45,1852,393.0,1132,349,2.7159,NEAR BAY
4596,-118.28,34.05,41,1788,774.0,2931,702,1.4413,<1H OCEAN
16287,-121.28,37.91,31,820,179.0,576,155,1.6900,INLAND
5771,-118.27,34.15,22,2265,637.0,1684,561,2.6729,<1H OCEAN
18254,-122.09,37.39,36,1035,196.0,475,205,5.5385,NEAR BAY